### ISSUE TITLE
support for hugging studio (free)

### ISSUE THREAD

**Issue by jaroslaw-weber** [insulineru/ai-commit#15]
hugging studio is free, so would be great if there was an option to choose.

btw is this repo still active?

**Comment by insulineru** [comment]
Hey, @jaroslaw-weber. Good idea!

You can open a Pull Request and make whatever changes you need to support that engine. If you have any questions or difficulties, you can write to me on Telegram or Twitter (links in my profile)

**Comment by jaroslaw-weber** [comment]
I have tried implement this but the response from the API was really bad so I abandoned this. Sorry. Maybe with the paid API it could work but that would defeat the purpose.

Is there any free API that can be used instead of open ai gpt ?

**Comment by insulineru** [comment]
> I have tried implement this but the response from the API was really bad so I abandoned this. Sorry. Maybe with the paid API it could work but that would defeat the purpose.
> 
> Is there any free API that can be used instead of open ai gpt ?

I stopped following AI models, but I think you can find LLama 2 (it's in opensource) or try with some other model with HuggingFace

**Comment by jaroslaw-weber** [comment]
hey, i made a PR for ollama support :) 
https://github.com/insulineru/ai-commit/pull/18 
which is a tool for running gpt like models locally.

**Comment by jaroslaw-weber** [comment]
we can close since we have free local model support now (ollama)
