### ISSUE TITLE
Ollama not recognized?

### ISSUE THREAD

**Issue by hansvangent** [insulineru/ai-commit#27]
I did the "ollama run mistral" and "export PROVIDER=ollama" but every time I try to run ai-commit I still get the error:

Please set the OPENAI_API_KEY environment variable.

I thought ollama was an alternative to OPENAI so you wouldn't need a key from OpenAI?

**Comment by ragmondo** [comment]
It looks as if the version that uses ollama hasn't been published yet. This isn't the right way but this is a working way of getting it working for me:

Clone this repo, cd into directory

```
export PROVIDER=ollama
npm audit fix
cd into-your-source-directory
node ../ai-commit/index.js # or supply absolute path

```
That last line you can create an alias for if you supply the absolute path.

**Comment by ragmondo** [comment]
Don't run the globally installed version of the code - run the version you checked out. If you look at `/usr/local/lib/node_modules/ai-commit/index.js` you'll see it's not the same as the one you just cloned.
